/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: denis_cliofas (https://sketchfab.com/denis_cliofas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/interogation-room-213c8cede7c846b2822b998b9726bec5
Title: Interogation Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Background(props) {
  const { nodes, materials } = useGLTF('/interogation_room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Walls_Walls_0.geometry}
        material={materials.Walls}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_Table_0.geometry}
        material={materials.Table}
        position={[1.476, 77.743, 3.235]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Chair_0.geometry}
        material={materials.Chair}
        position={[-13.536, 0.019, 57.982]}
        rotation={[Math.PI, -1.295, -Math.PI]}
        scale={0.396}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair001_Chair_0.geometry}
        material={materials.Chair}
        position={[4.381, 0.019, -45.132]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.396}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Watch_Watch_0.geometry}
        material={materials.Watch}
        position={[-157.887, 192.749, 183.641]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_Door_0.geometry}
        material={materials.Door}
        position={[40.635, 0, 303.196]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Window_0.geometry}
        material={materials.Window}
        position={[154.73, 167.839, 79.536]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Switch_Switch_0.geometry}
        material={materials.Switch}
        position={[-35.196, 120.613, 295.468]}
        scale={0.067}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Neon_Tubes_Lamp_0.geometry}
        material={materials.Lamp}
        position={[62.008, 270.154, 99.73]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Neon_Tubes001_Lamp_0.geometry}
        material={materials.Lamp}
        position={[62.008, 270.154, -85.795]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Surveillance_Camera_Camera_0.geometry}
        material={materials.Camera}
        position={[-6.901, 235.143, 273.082]}
        scale={0.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Papers_Papers_0.geometry}
        material={materials.Papers}
        position={[-1.876, 81.222, 19.89]}
        rotation={[0, 0.702, 0]}
        scale={[0.078, 0.135, 0.116]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handcuffs_Handcuffs_0.geometry}
        material={materials.Handcuffs}
        position={[34.145, 81.437, -7.426]}
        rotation={[-Math.PI, 0.643, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Background_Background_0.geometry}
        material={materials.Background}
      />
    </group>
  )
}

useGLTF.preload('/interogation_room.glb')